AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ordersapi

  Sample SAM Template for ordersapi

Resources:
  CreateOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ordersapi
      Handler: com.aws.lambda.api.CreateOrderLambda::createOrder
      Runtime: java8
      MemorySize: 512
      Events:
        OrderEvent:
          Type: Api
          Properties:
            Path: /orders
            Method: post
             
  ReadOrdersFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ordersapi
      Handler: com.aws.lambda.api..ReadOrdersLambda::getOrders
      Runtime: java8
      MemorySize: 512
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: GET